# Generated by Django 5.2.1 on 2025-06-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habittarget',
            name='value',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
