# Generated by Django 5.2.1 on 2025-06-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_userassessmentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
